
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: severe_incident_development

test:
  <<: *default
  database: severe_incident_test

production:
  <<: *default
  database: severe_incident_production
  username: severe_incident
  password: <%= ENV['SEVERE_INCIDENT_DATABASE_PASSWORD'] %>
